package com.adu.spring_test.webservice.hello.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-15T20:51:59.383+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://service.cxf.com/", name = "HelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWS {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.cxf.com/", className = "com.adu.spring_test.webservice.hello.model.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.cxf.com/", className = "com.adu.spring_test.webservice.hello.model.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://service.cxf.com/", className = "com.adu.spring_test.webservice.hello.model.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://service.cxf.com/", className = "com.adu.spring_test.webservice.hello.model.AddUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.adu.spring_test.webservice.hello.model.User addUser(
        @WebParam(name = "user", targetNamespace = "")
        com.adu.spring_test.webservice.hello.model.User user
    );
}
