package com.adu.spring_test.webservice.email.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-15T20:40:01.343+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "ValidateEmailWebServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ValidateEmailWebServiceHttpPost {

    /**
     * <br /><h3>验证 Email 地址是否正确</h3><p>输入参数：EmailAddress = Email 地址（默认SMTP端口25），返回数据： Byte 字节。返回值： 0 = 请重新验证；1 = 邮件地址合法；2 = 只是域名正确；3 = 一个未知错误；4 = 邮件服务器没有找到；5 = 电子邮件地址错误；6 = 免费用户验证超过数量（50次/24小时）；7 = 商业用户不能通过验证</p><br />
     */
    @WebMethod(operationName = "ValidateEmailAddress")
    @WebResult(name = "unsignedByte", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public short validateEmailAddress(
        @WebParam(partName = "theEmail", name = "theEmail", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theEmail
    );

    /**
     * <br /><h3>验证 Email 地址是否正确</h3><p>输入参数：EmailAddress = Email 地址，theEmailPort = SMTP端口（Integer），返回数据： Byte 字节。返回值同 ValidateEmailAddress</p><br />
     */
    @WebMethod(operationName = "ValidateEmailAddressPro")
    @WebResult(name = "unsignedByte", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public short validateEmailAddressPro(
        @WebParam(partName = "theEmail", name = "theEmail", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theEmail,
        @WebParam(partName = "theEmailPort", name = "theEmailPort", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theEmailPort
    );
}
